/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tela;

/**
 *
 * @author Felipe, Hudson e Thiago
 */

import com.calcular.Basico;
import com.calcular.Avancado;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


public class TelaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("calculadora.png")));
        initComponents();
        this.setLocationRelativeTo(null);
        btnApagar.setVisible(false);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCalc = new javax.swing.JPanel();
        bgAlteraModo = new javax.swing.JPanel();
        titleCalc = new javax.swing.JLabel();
        displaySec = new javax.swing.JLabel();
        displayPrinc = new javax.swing.JLabel();
        bg14Multi = new javax.swing.JPanel();
        btnMulti = new javax.swing.JLabel();
        bg24Menos = new javax.swing.JPanel();
        btnMenos = new javax.swing.JLabel();
        bg22Seis = new javax.swing.JPanel();
        btnSeis = new javax.swing.JLabel();
        bg11Oito = new javax.swing.JPanel();
        btnOito = new javax.swing.JLabel();
        bg21Cinco = new javax.swing.JPanel();
        btnCinco = new javax.swing.JLabel();
        bg20Quatro = new javax.swing.JPanel();
        btnQuatro = new javax.swing.JLabel();
        bg12Nove = new javax.swing.JPanel();
        btnNove = new javax.swing.JLabel();
        bg10Sete = new javax.swing.JPanel();
        btnSete = new javax.swing.JLabel();
        bg30Um = new javax.swing.JPanel();
        btnUm = new javax.swing.JLabel();
        bg31Dois = new javax.swing.JPanel();
        btnDois = new javax.swing.JLabel();
        bg32Tres = new javax.swing.JPanel();
        btnTres = new javax.swing.JLabel();
        bg40MaisMenos = new javax.swing.JPanel();
        btnMaisMenos = new javax.swing.JLabel();
        bg41Zero = new javax.swing.JPanel();
        btnZero = new javax.swing.JLabel();
        bg42Virg = new javax.swing.JPanel();
        btnVirgula = new javax.swing.JLabel();
        bg33Mais = new javax.swing.JPanel();
        btnMais = new javax.swing.JLabel();
        bg43Igual = new javax.swing.JPanel();
        btnIgual = new javax.swing.JLabel();
        bg00C = new javax.swing.JPanel();
        btnResetTela1 = new javax.swing.JLabel();
        bg01Raiz = new javax.swing.JPanel();
        btnRaiz = new javax.swing.JLabel();
        bg04Div = new javax.swing.JPanel();
        btnDivisao = new javax.swing.JLabel();
        bg02Pot = new javax.swing.JPanel();
        btnPot = new javax.swing.JLabel();
        bgThemeMode = new javax.swing.JPanel();
        btnThemeMode = new javax.swing.JLabel();
        bgApagar = new javax.swing.JPanel();
        btnApagar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgCalc.setBackground(new java.awt.Color(20, 20, 20));
        bgCalc.setForeground(new java.awt.Color(204, 204, 204));

        bgAlteraModo.setBackground(new java.awt.Color(20, 20, 20));

        javax.swing.GroupLayout bgAlteraModoLayout = new javax.swing.GroupLayout(bgAlteraModo);
        bgAlteraModo.setLayout(bgAlteraModoLayout);
        bgAlteraModoLayout.setHorizontalGroup(
            bgAlteraModoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );
        bgAlteraModoLayout.setVerticalGroup(
            bgAlteraModoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        titleCalc.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        titleCalc.setForeground(new java.awt.Color(255, 245, 212));
        titleCalc.setText("Padrão");

        displaySec.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        displaySec.setForeground(new java.awt.Color(255, 245, 200));
        displaySec.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        displaySec.setText("0");
        displaySec.setToolTipText("");
        displaySec.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        displayPrinc.setFont(new java.awt.Font("Calibri", 0, 52)); // NOI18N
        displayPrinc.setForeground(new java.awt.Color(224, 243, 231));
        displayPrinc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        displayPrinc.setText("0");
        displayPrinc.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        bg14Multi.setBackground(new java.awt.Color(255, 255, 153));
        bg14Multi.setPreferredSize(new java.awt.Dimension(80, 80));

        btnMulti.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnMulti.setForeground(new java.awt.Color(0, 0, 0));
        btnMulti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMulti.setText("×");
        btnMulti.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMulti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMultiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg14MultiLayout = new javax.swing.GroupLayout(bg14Multi);
        bg14Multi.setLayout(bg14MultiLayout);
        bg14MultiLayout.setHorizontalGroup(
            bg14MultiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMulti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        bg14MultiLayout.setVerticalGroup(
            bg14MultiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMulti, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        bg24Menos.setBackground(new java.awt.Color(255, 255, 153));
        bg24Menos.setPreferredSize(new java.awt.Dimension(80, 80));

        btnMenos.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnMenos.setForeground(new java.awt.Color(0, 0, 0));
        btnMenos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMenos.setText("-");
        btnMenos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg24MenosLayout = new javax.swing.GroupLayout(bg24Menos);
        bg24Menos.setLayout(bg24MenosLayout);
        bg24MenosLayout.setHorizontalGroup(
            bg24MenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(bg24MenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnMenos, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        bg24MenosLayout.setVerticalGroup(
            bg24MenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
            .addGroup(bg24MenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnMenos, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
        );

        bg22Seis.setBackground(new java.awt.Color(30, 30, 30));
        bg22Seis.setPreferredSize(new java.awt.Dimension(80, 80));

        btnSeis.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnSeis.setForeground(new java.awt.Color(255, 255, 255));
        btnSeis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSeis.setText("6");
        btnSeis.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSeis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg22SeisLayout = new javax.swing.GroupLayout(bg22Seis);
        bg22Seis.setLayout(bg22SeisLayout);
        bg22SeisLayout.setHorizontalGroup(
            bg22SeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(bg22SeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnSeis, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        bg22SeisLayout.setVerticalGroup(
            bg22SeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
            .addGroup(bg22SeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnSeis, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
        );

        bg11Oito.setBackground(new java.awt.Color(30, 30, 30));
        bg11Oito.setPreferredSize(new java.awt.Dimension(80, 80));

        btnOito.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnOito.setForeground(new java.awt.Color(255, 255, 255));
        btnOito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnOito.setText("8");
        btnOito.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnOito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOitoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg11OitoLayout = new javax.swing.GroupLayout(bg11Oito);
        bg11Oito.setLayout(bg11OitoLayout);
        bg11OitoLayout.setHorizontalGroup(
            bg11OitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnOito, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        bg11OitoLayout.setVerticalGroup(
            bg11OitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnOito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg21Cinco.setBackground(new java.awt.Color(30, 30, 30));
        bg21Cinco.setPreferredSize(new java.awt.Dimension(80, 80));

        btnCinco.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnCinco.setForeground(new java.awt.Color(255, 255, 255));
        btnCinco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCinco.setText("5");
        btnCinco.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCincoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg21CincoLayout = new javax.swing.GroupLayout(bg21Cinco);
        bg21Cinco.setLayout(bg21CincoLayout);
        bg21CincoLayout.setHorizontalGroup(
            bg21CincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCinco, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        bg21CincoLayout.setVerticalGroup(
            bg21CincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg20Quatro.setBackground(new java.awt.Color(30, 30, 30));
        bg20Quatro.setPreferredSize(new java.awt.Dimension(80, 80));

        btnQuatro.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnQuatro.setForeground(new java.awt.Color(255, 255, 255));
        btnQuatro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQuatro.setText("4");
        btnQuatro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnQuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuatroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg20QuatroLayout = new javax.swing.GroupLayout(bg20Quatro);
        bg20Quatro.setLayout(bg20QuatroLayout);
        bg20QuatroLayout.setHorizontalGroup(
            bg20QuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQuatro, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        bg20QuatroLayout.setVerticalGroup(
            bg20QuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQuatro, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        bg12Nove.setBackground(new java.awt.Color(30, 30, 30));
        bg12Nove.setPreferredSize(new java.awt.Dimension(80, 80));

        btnNove.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnNove.setForeground(new java.awt.Color(255, 255, 255));
        btnNove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNove.setText("9");
        btnNove.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnNove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNoveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg12NoveLayout = new javax.swing.GroupLayout(bg12Nove);
        bg12Nove.setLayout(bg12NoveLayout);
        bg12NoveLayout.setHorizontalGroup(
            bg12NoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNove, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        bg12NoveLayout.setVerticalGroup(
            bg12NoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNove, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        bg10Sete.setBackground(new java.awt.Color(30, 30, 30));
        bg10Sete.setPreferredSize(new java.awt.Dimension(80, 80));

        btnSete.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnSete.setForeground(new java.awt.Color(255, 255, 255));
        btnSete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSete.setText("7");
        btnSete.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg10SeteLayout = new javax.swing.GroupLayout(bg10Sete);
        bg10Sete.setLayout(bg10SeteLayout);
        bg10SeteLayout.setHorizontalGroup(
            bg10SeteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSete, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        bg10SeteLayout.setVerticalGroup(
            bg10SeteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg10SeteLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(btnSete))
        );

        bg30Um.setBackground(new java.awt.Color(30, 30, 30));
        bg30Um.setPreferredSize(new java.awt.Dimension(80, 80));

        btnUm.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnUm.setForeground(new java.awt.Color(255, 255, 255));
        btnUm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUm.setText("1");
        btnUm.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnUm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUmMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUmMousePressed(evt);
            }
        });

        javax.swing.GroupLayout bg30UmLayout = new javax.swing.GroupLayout(bg30Um);
        bg30Um.setLayout(bg30UmLayout);
        bg30UmLayout.setHorizontalGroup(
            bg30UmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(bg30UmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnUm, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        bg30UmLayout.setVerticalGroup(
            bg30UmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(bg30UmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnUm, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
        );

        bg31Dois.setBackground(new java.awt.Color(30, 30, 30));
        bg31Dois.setPreferredSize(new java.awt.Dimension(80, 80));

        btnDois.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnDois.setForeground(new java.awt.Color(255, 255, 255));
        btnDois.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDois.setText("2");
        btnDois.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnDois.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg31DoisLayout = new javax.swing.GroupLayout(bg31Dois);
        bg31Dois.setLayout(bg31DoisLayout);
        bg31DoisLayout.setHorizontalGroup(
            bg31DoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(bg31DoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnDois, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        bg31DoisLayout.setVerticalGroup(
            bg31DoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(bg31DoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnDois, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
        );

        bg32Tres.setBackground(new java.awt.Color(30, 30, 30));
        bg32Tres.setPreferredSize(new java.awt.Dimension(80, 80));

        btnTres.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnTres.setForeground(new java.awt.Color(255, 255, 255));
        btnTres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTres.setText("3");
        btnTres.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTresMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg32TresLayout = new javax.swing.GroupLayout(bg32Tres);
        bg32Tres.setLayout(bg32TresLayout);
        bg32TresLayout.setHorizontalGroup(
            bg32TresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(bg32TresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnTres, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        bg32TresLayout.setVerticalGroup(
            bg32TresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(bg32TresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnTres, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
        );

        bg40MaisMenos.setBackground(new java.awt.Color(30, 30, 30));
        bg40MaisMenos.setPreferredSize(new java.awt.Dimension(80, 80));

        btnMaisMenos.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnMaisMenos.setForeground(new java.awt.Color(255, 255, 255));
        btnMaisMenos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMaisMenos.setText("±");
        btnMaisMenos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMaisMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaisMenosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg40MaisMenosLayout = new javax.swing.GroupLayout(bg40MaisMenos);
        bg40MaisMenos.setLayout(bg40MaisMenosLayout);
        bg40MaisMenosLayout.setHorizontalGroup(
            bg40MaisMenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(bg40MaisMenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnMaisMenos, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        bg40MaisMenosLayout.setVerticalGroup(
            bg40MaisMenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(bg40MaisMenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnMaisMenos, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );

        bg41Zero.setBackground(new java.awt.Color(30, 30, 30));
        bg41Zero.setPreferredSize(new java.awt.Dimension(80, 80));

        btnZero.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnZero.setForeground(new java.awt.Color(255, 255, 255));
        btnZero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnZero.setText("0");
        btnZero.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnZero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnZeroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg41ZeroLayout = new javax.swing.GroupLayout(bg41Zero);
        bg41Zero.setLayout(bg41ZeroLayout);
        bg41ZeroLayout.setHorizontalGroup(
            bg41ZeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(bg41ZeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnZero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        bg41ZeroLayout.setVerticalGroup(
            bg41ZeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(bg41ZeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnZero, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
        );

        bg42Virg.setBackground(new java.awt.Color(30, 30, 30));
        bg42Virg.setPreferredSize(new java.awt.Dimension(80, 80));

        btnVirgula.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnVirgula.setForeground(new java.awt.Color(255, 255, 255));
        btnVirgula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVirgula.setText(",");
        btnVirgula.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnVirgula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVirgulaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg42VirgLayout = new javax.swing.GroupLayout(bg42Virg);
        bg42Virg.setLayout(bg42VirgLayout);
        bg42VirgLayout.setHorizontalGroup(
            bg42VirgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(bg42VirgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnVirgula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        bg42VirgLayout.setVerticalGroup(
            bg42VirgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(bg42VirgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnVirgula, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
        );

        bg33Mais.setBackground(new java.awt.Color(255, 255, 153));
        bg33Mais.setPreferredSize(new java.awt.Dimension(80, 80));

        btnMais.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnMais.setForeground(new java.awt.Color(0, 0, 0));
        btnMais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMais.setText("+");
        btnMais.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg33MaisLayout = new javax.swing.GroupLayout(bg33Mais);
        bg33Mais.setLayout(bg33MaisLayout);
        bg33MaisLayout.setHorizontalGroup(
            bg33MaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(bg33MaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnMais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        bg33MaisLayout.setVerticalGroup(
            bg33MaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
            .addGroup(bg33MaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnMais, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
        );

        bg43Igual.setBackground(new java.awt.Color(255, 204, 102));
        bg43Igual.setPreferredSize(new java.awt.Dimension(80, 80));

        btnIgual.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnIgual.setForeground(new java.awt.Color(0, 0, 0));
        btnIgual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnIgual.setText("=");
        btnIgual.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIgualMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg43IgualLayout = new javax.swing.GroupLayout(bg43Igual);
        bg43Igual.setLayout(bg43IgualLayout);
        bg43IgualLayout.setHorizontalGroup(
            bg43IgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(bg43IgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnIgual, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        bg43IgualLayout.setVerticalGroup(
            bg43IgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
            .addGroup(bg43IgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnIgual, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
        );

        bg00C.setBackground(new java.awt.Color(40, 40, 40));
        bg00C.setPreferredSize(new java.awt.Dimension(80, 80));

        btnResetTela1.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnResetTela1.setForeground(new java.awt.Color(255, 255, 255));
        btnResetTela1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnResetTela1.setText("C");
        btnResetTela1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnResetTela1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetTela1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg00CLayout = new javax.swing.GroupLayout(bg00C);
        bg00C.setLayout(bg00CLayout);
        bg00CLayout.setHorizontalGroup(
            bg00CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnResetTela1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        bg00CLayout.setVerticalGroup(
            bg00CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnResetTela1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        bg01Raiz.setBackground(new java.awt.Color(40, 40, 40));
        bg01Raiz.setPreferredSize(new java.awt.Dimension(80, 80));

        btnRaiz.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnRaiz.setForeground(new java.awt.Color(255, 255, 255));
        btnRaiz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRaiz.setText("√");
        btnRaiz.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRaiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRaizMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg01RaizLayout = new javax.swing.GroupLayout(bg01Raiz);
        bg01Raiz.setLayout(bg01RaizLayout);
        bg01RaizLayout.setHorizontalGroup(
            bg01RaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        bg01RaizLayout.setVerticalGroup(
            bg01RaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRaiz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        bg04Div.setBackground(new java.awt.Color(255, 255, 153));
        bg04Div.setPreferredSize(new java.awt.Dimension(80, 80));

        btnDivisao.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnDivisao.setForeground(new java.awt.Color(0, 0, 0));
        btnDivisao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDivisao.setText("÷");
        btnDivisao.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnDivisao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDivisaoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg04DivLayout = new javax.swing.GroupLayout(bg04Div);
        bg04Div.setLayout(bg04DivLayout);
        bg04DivLayout.setHorizontalGroup(
            bg04DivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDivisao, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        bg04DivLayout.setVerticalGroup(
            bg04DivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDivisao, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        bg02Pot.setBackground(new java.awt.Color(40, 40, 40));
        bg02Pot.setPreferredSize(new java.awt.Dimension(80, 80));

        btnPot.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnPot.setForeground(new java.awt.Color(255, 255, 255));
        btnPot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPot.setText("x²");
        btnPot.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPotMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bg02PotLayout = new javax.swing.GroupLayout(bg02Pot);
        bg02Pot.setLayout(bg02PotLayout);
        bg02PotLayout.setHorizontalGroup(
            bg02PotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(bg02PotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnPot, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        bg02PotLayout.setVerticalGroup(
            bg02PotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(bg02PotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnPot, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
        );

        bgThemeMode.setBackground(new java.awt.Color(255, 245, 212));

        btnThemeMode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThemeMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/theme.png"))); // NOI18N
        btnThemeMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemeModeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bgThemeModeLayout = new javax.swing.GroupLayout(bgThemeMode);
        bgThemeMode.setLayout(bgThemeModeLayout);
        bgThemeModeLayout.setHorizontalGroup(
            bgThemeModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgThemeModeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemeMode, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );
        bgThemeModeLayout.setVerticalGroup(
            bgThemeModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgThemeModeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemeMode, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgApagar.setBackground(new java.awt.Color(20, 20, 20));
        bgApagar.setPreferredSize(new java.awt.Dimension(80, 80));

        btnApagar.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnApagar.setForeground(new java.awt.Color(255, 255, 255));
        btnApagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnApagar.setText("<<");
        btnApagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnApagarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bgApagarLayout = new javax.swing.GroupLayout(bgApagar);
        bgApagar.setLayout(bgApagarLayout);
        bgApagarLayout.setHorizontalGroup(
            bgApagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnApagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        bgApagarLayout.setVerticalGroup(
            bgApagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnApagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bgCalcLayout = new javax.swing.GroupLayout(bgCalc);
        bgCalc.setLayout(bgCalcLayout);
        bgCalcLayout.setHorizontalGroup(
            bgCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgCalcLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(bgCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgCalcLayout.createSequentialGroup()
                        .addComponent(bg40MaisMenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bg41Zero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bg42Virg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bg43Igual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgCalcLayout.createSequentialGroup()
                        .addComponent(bg30Um, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bg31Dois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bg32Tres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bg33Mais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgCalcLayout.createSequentialGroup()
                        .addComponent(bg10Sete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bg11Oito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bg12Nove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bg14Multi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgCalcLayout.createSequentialGroup()
                        .addComponent(bg20Quatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bg21Cinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bg22Seis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bg24Menos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgCalcLayout.createSequentialGroup()
                            .addComponent(titleCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bgAlteraModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bgThemeMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(displayPrinc, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                        .addComponent(displaySec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bgCalcLayout.createSequentialGroup()
                        .addComponent(bg00C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bg01Raiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bg02Pot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bgApagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bg04Div, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        bgCalcLayout.setVerticalGroup(
            bgCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgCalcLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(bgCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bgAlteraModo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bgThemeMode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displaySec, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bgApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgCalcLayout.createSequentialGroup()
                        .addGroup(bgCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bg00C, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bg01Raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bg04Div, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bgCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bg10Sete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                .addComponent(bg11Oito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                .addComponent(bg14Multi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bg12Nove, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bg24Menos, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(bg21Cinco, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(bg22Seis, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(bg20Quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bg30Um, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bg31Dois, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bg32Tres, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bg33Mais, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bg40MaisMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bg41Zero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bg42Virg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bg43Igual, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(bgCalcLayout.createSequentialGroup()
                        .addComponent(bg02Pot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String []funcao = new String[4]; //Funcao, expressão do calculo
    
    public String numero1 = ""; //vai receber a string antes de clicar em op
    public String teclaDigitada = ""; // aramazena a ultima tecla clicada
    public String numero2 = ""; //vai receber a string após o op for identificado
    public String op = ""; // armazena que tipo de operação é
    public String digitado = ""; //armazena a String que foi digitada no teclado
    public String ultOp = ""; // ultima operação feita
    public String saida = ""; // saida de resultados na tela
    public String saidaSec = "";    
    
    public double resSoma = 0; //soma dos resultados
    
    public int contFuncao = 0; // contagem de posicao no vetor Funcao
    public int contOp = 0; // contagem de quantas operacoes contém dentro do vetor Funcao
    
    public boolean verifIgual = false;
    public boolean virgula = false;
    public boolean darkTheme = false; 
    
    Basico bas = new Basico();
    Avancado adv = new Avancado();
    
    public void theme(boolean th){
        this.darkTheme = th;
        
        if (darkTheme == true) {
            
            //Cor linha topo teclado BACKGROUD
            bgCalc.setBackground(new java.awt.Color(20, 20, 20));
            bg00C.setBackground(new java.awt.Color(40, 40, 40));
            bg01Raiz.setBackground(new java.awt.Color(40, 40, 40));
            bg02Pot.setBackground(new java.awt.Color(40, 40, 40));

            //Cor linha topo teclado LETRAS
            btnResetTela1.setForeground(new java.awt.Color(255,255,255));
            btnPot.setForeground(new java.awt.Color(255,255,255));
            btnRaiz.setForeground(new java.awt.Color(255,255,255));

            //Cor teclado numerico BACKGROUND
            bg10Sete.setBackground(new java.awt.Color(30, 30, 30));
            bg11Oito.setBackground(new java.awt.Color(30, 30, 30));
            bg12Nove.setBackground(new java.awt.Color(30, 30, 30));
            bg20Quatro.setBackground(new java.awt.Color(30, 30, 30));
            bg21Cinco.setBackground(new java.awt.Color(30, 30, 30));
            bg22Seis.setBackground(new java.awt.Color(30, 30, 30));
            bg30Um.setBackground(new java.awt.Color(30, 30, 30));
            bg31Dois.setBackground(new java.awt.Color(30, 30, 30));
            bg32Tres.setBackground(new java.awt.Color(30, 30, 30));
            bg40MaisMenos.setBackground(new java.awt.Color(30, 30, 30));
            bg41Zero.setBackground(new java.awt.Color(30, 30, 30));
            bg42Virg.setBackground(new java.awt.Color(30, 30, 30));

            //Cor teclado numerico LETRAS
            btnSete.setForeground(new java.awt.Color(255, 255, 255));
            btnOito.setForeground(new java.awt.Color(255, 255, 255));
            btnNove.setForeground(new java.awt.Color(255, 255, 255));
            btnQuatro.setForeground(new java.awt.Color(255, 255, 255));
            btnCinco.setForeground(new java.awt.Color(255, 255, 255));
            btnSeis.setForeground(new java.awt.Color(255, 255, 255));
            btnUm.setForeground(new java.awt.Color(255, 255, 255));
            btnDois.setForeground(new java.awt.Color(255, 255, 255));
            btnTres.setForeground(new java.awt.Color(255, 255, 255));
            btnMaisMenos.setForeground(new java.awt.Color(255, 255, 255));
            btnZero.setForeground(new java.awt.Color(255, 255, 255));
            btnVirgula.setForeground(new java.awt.Color(255, 255, 255));

            //Cor bg operacoes
            bg04Div.setBackground(new java.awt.Color(255,255,153));
            bg14Multi.setBackground(new java.awt.Color(255,255,153));
            bg24Menos.setBackground(new java.awt.Color(255,255,153));
            bg33Mais.setBackground(new java.awt.Color(255,255,153));

            //Cor botao Igual
            bg43Igual.setBackground(new java.awt.Color(255, 204, 102));
            btnIgual.setForeground(new java.awt.Color(0,0,0));

            //cor Display
            displayPrinc.setForeground(new java.awt.Color(224,243,231));
            displaySec.setForeground(new java.awt.Color(255,245,200));
            titleCalc.setForeground(new java.awt.Color(255,245,212));
            bgThemeMode.setBackground(new java.awt.Color(255,245,212));
            btnApagar.setForeground(new java.awt.Color(255,255,255));
            bgApagar.setBackground(new java.awt.Color(20, 20, 20));
            bgAlteraModo.setBackground(new java.awt.Color(20, 20, 20));
            
            darkTheme = false;
            
            
        } else {
            
            //Cor linha topo teclado BACKGROUD
            bgCalc.setBackground(new java.awt.Color(253, 253, 253));
            bg00C.setBackground(new java.awt.Color(239, 239, 239));
            bg01Raiz.setBackground(new java.awt.Color(239, 239, 239));
            bg02Pot.setBackground(new java.awt.Color(239, 239, 239));
            
            //Cor linha topo teclado LETRAS
            btnResetTela1.setForeground(new java.awt.Color(0, 0, 50));
            btnPot.setForeground(new java.awt.Color(0, 0, 50));
            btnRaiz.setForeground(new java.awt.Color(0, 0, 50));
            
            //Cor teclado numerico BACKGROUND
            bg10Sete.setBackground(new java.awt.Color(240, 240, 240));
            bg11Oito.setBackground(new java.awt.Color(240, 240, 240));
            bg12Nove.setBackground(new java.awt.Color(240, 240, 240));
            bg20Quatro.setBackground(new java.awt.Color(240, 240, 240));
            bg21Cinco.setBackground(new java.awt.Color(240, 240, 240));
            bg22Seis.setBackground(new java.awt.Color(240, 240, 240));
            bg30Um.setBackground(new java.awt.Color(240, 240, 240));
            bg31Dois.setBackground(new java.awt.Color(240, 240, 240));
            bg32Tres.setBackground(new java.awt.Color(240, 240, 240));
            bg40MaisMenos.setBackground(new java.awt.Color(240, 240, 240));
            bg41Zero.setBackground(new java.awt.Color(240, 240, 240));
            bg42Virg.setBackground(new java.awt.Color(240, 240, 240));
            
            //Cor teclado numerico LETRAS
            btnSete.setForeground(new java.awt.Color(0, 0, 50));
            btnOito.setForeground(new java.awt.Color(0, 0, 50));
            btnNove.setForeground(new java.awt.Color(0, 0, 50));
            btnQuatro.setForeground(new java.awt.Color(0, 0, 50));
            btnCinco.setForeground(new java.awt.Color(0, 0, 50));
            btnSeis.setForeground(new java.awt.Color(0, 0, 50));
            btnUm.setForeground(new java.awt.Color(0, 0, 50));
            btnDois.setForeground(new java.awt.Color(0, 0, 50));
            btnTres.setForeground(new java.awt.Color(0, 0, 50));
            btnMaisMenos.setForeground(new java.awt.Color(0, 0, 50));
            btnZero.setForeground(new java.awt.Color(0, 0, 50));
            btnVirgula.setForeground(new java.awt.Color(0, 0, 50));
            
            //Cor bg operacoes
            bg04Div.setBackground(new java.awt.Color(0, 210, 255));
            bg14Multi.setBackground(new java.awt.Color(0, 210, 255));
            bg24Menos.setBackground(new java.awt.Color(0, 210, 255));
            bg33Mais.setBackground(new java.awt.Color(0, 210, 255));
            
            //Cor botao Igual
            bg43Igual.setBackground(new java.awt.Color(0, 150, 255));
            btnIgual.setForeground(new java.awt.Color(255, 255, 255));
            
            //cor Display
            displayPrinc.setForeground(new java.awt.Color(0, 0, 100));
            displaySec.setForeground(new java.awt.Color(0, 200, 255));
            titleCalc.setForeground(new java.awt.Color(0, 150, 255));
            bgThemeMode.setBackground(new java.awt.Color(255, 255, 255));
            btnApagar.setForeground(new java.awt.Color(0, 0, 50));
            bgApagar.setBackground(new java.awt.Color(255, 255, 255));
            bgAlteraModo.setBackground(new java.awt.Color(255, 255, 255));
            
            darkTheme = true;
        }
    }
    
    public void limpeza() {
        numero1 = "";
        op = "";
        numero2 = "";
        saida = "";
        saidaSec="";
        digitado = "";
        teclaDigitada = "";
        btnApagar.setVisible(false);
    }
    

    public void igual(){
        try {
            if (op.equals("+")) resSoma = bas.Somar(numero1, numero2);
            if (op.equals("-")) resSoma = bas.Subt(numero1, numero2);
            if (op.equals("/")) resSoma = bas.Div(numero1, numero2);
            if (op.equals("x")) resSoma = bas.Multi(numero1, numero2);
            if (op.equals("√")) resSoma = adv.Raiz(numero1);
            if (op.equals("p")) resSoma = adv.Pot(numero1);
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro+" | Digite um número válido!");
        }
        
        verifIgual = true;
        
        if (resSoma - ((int) (resSoma)) > 0) {
            saida = resSoma + "";
        } else {
            saida = resSoma + "";
            saida = saida.replace(".0", "");
        }

        // IMPORTANTE >>> VERIFICAR DÍZIMA PERIÓDICA | NUMEROS MAIORES QUE 12 DIGITOS
        if (saida.length() > 12) {
            String s = "";
            for (int i = 0; i < 12; i++) {
                s += saida.charAt(i);
            }
            saida = s;
        }
        
        if (op.equals("√")){
            saidaSec = saidaSec.replace("√","");
            saidaSec = "√"+saidaSec;
        }

        displayPrinc.setText(saida);
        displaySec.setText(saidaSec.replace("p","²"));
        
        limpeza();
        op = "";
    }
    
    
    //realiza as op mais básicas
    public void salvaExpressao(String tc){
                
        this.teclaDigitada = tc; //guarda no escopo de classe
        
        //limita a entrada de dígitos na calculadora
        if (digitado.length() < 12) {
            digitado += teclaDigitada;
        }
        
        //Efeito botao apagar some ou aparece
        if (displayPrinc.equals("")) {
            btnApagar.setVisible(false);
        } else {
            btnApagar.setVisible(true);
        }
        
        //verifica se operacao é uma raiz
        if (teclaDigitada.equals("√")){
            this.op = teclaDigitada;
        }
        
        //verifica se operacao é uma potencia
        if (teclaDigitada.equals("p")){
            this.op = teclaDigitada;
        }

        //verifica se tecla é uma operacao
        
        if (teclaDigitada.equals("√") || teclaDigitada.equals("p") || teclaDigitada.equals("+") || teclaDigitada.equals("x") || teclaDigitada.equals("-") || teclaDigitada.equals("/")) {
                    
            op = teclaDigitada;
            this.numero1 = digitado.replace(op,"");
            
            if (numero1.equals("")){
                numero1 = resSoma+"";
                numero1 = numero1.replace(".0","");
            }
            
            
            digitado = "";

            saidaSec += numero1+op.replace("=","");
            displaySec.setText(saidaSec.replace("p","²"));
            
            virgula = false;
            
            if (teclaDigitada.equals("p")) igual();
            if (teclaDigitada.equals("√")) igual();
            
        } else {
            if (teclaDigitada.equals("=")) {
                this.numero2 = digitado.replace("=","");
                saidaSec += numero2;
                this.numero2 = numero2.replace("√","");
                this.numero2 = numero2.replace("p","");
                igual();
                
                virgula = false;
               
            } else {                
                displayPrinc.setText(digitado);
            }
        }   
        
    }
        
    
    
    public void apagarDig(){
        digitado = digitado.substring(0, digitado.length()-1);
        displayPrinc.setText(digitado);
    }
    
    private void btnDivisaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivisaoMouseClicked
        salvaExpressao("/");
    }//GEN-LAST:event_btnDivisaoMouseClicked

    private void btnSeteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeteMouseClicked
        salvaExpressao("7"); 
    }//GEN-LAST:event_btnSeteMouseClicked

    private void btnOitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOitoMouseClicked
        salvaExpressao("8");
    }//GEN-LAST:event_btnOitoMouseClicked

    private void btnNoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoveMouseClicked
        salvaExpressao("9");
    }//GEN-LAST:event_btnNoveMouseClicked

    private void btnQuatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuatroMouseClicked
        salvaExpressao("4");
    }//GEN-LAST:event_btnQuatroMouseClicked

    private void btnCincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCincoMouseClicked
        salvaExpressao("5");
    }//GEN-LAST:event_btnCincoMouseClicked

    private void btnSeisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeisMouseClicked
        salvaExpressao("6");
    }//GEN-LAST:event_btnSeisMouseClicked

    private void btnUmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUmMouseClicked
        //salvaExpressao("1");
    }//GEN-LAST:event_btnUmMouseClicked

    private void btnDoisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoisMouseClicked
        salvaExpressao("2");
    }//GEN-LAST:event_btnDoisMouseClicked

    private void btnTresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTresMouseClicked
        salvaExpressao("3");
    }//GEN-LAST:event_btnTresMouseClicked

    private void btnZeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnZeroMouseClicked
        salvaExpressao("0");
    }//GEN-LAST:event_btnZeroMouseClicked

    private void btnMaisMenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaisMenosMouseClicked
        digitado = displayPrinc.getText();
        if (digitado.charAt(0) != '√'){
            if (digitado.charAt(0) != '-') {
                digitado = "-" + digitado;
            } else {
                digitado = digitado.replace("-", "");
            }
        }
        
        displayPrinc.setText(digitado);
    }//GEN-LAST:event_btnMaisMenosMouseClicked

    private void btnVirgulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVirgulaMouseClicked
        if (virgula==false) {
            salvaExpressao(".");
            virgula=true;
        }
    }//GEN-LAST:event_btnVirgulaMouseClicked

    private void btnMultiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiMouseClicked
        salvaExpressao("x");
    }//GEN-LAST:event_btnMultiMouseClicked

    private void btnMenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosMouseClicked
        salvaExpressao("-");
    }//GEN-LAST:event_btnMenosMouseClicked

    private void btnMaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaisMouseClicked
        salvaExpressao("+");
    }//GEN-LAST:event_btnMaisMouseClicked

    private void btnIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIgualMouseClicked
        salvaExpressao("=");
    }//GEN-LAST:event_btnIgualMouseClicked

    private void btnThemeModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemeModeMouseClicked
        if (darkTheme == true) {
            theme(true);
        } else {
            theme(false);
        }
        
    }//GEN-LAST:event_btnThemeModeMouseClicked

    private void btnUmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUmMousePressed
        salvaExpressao("1");
    }//GEN-LAST:event_btnUmMousePressed

    private void btnRaizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRaizMouseClicked
        salvaExpressao("√");
    }//GEN-LAST:event_btnRaizMouseClicked

    private void btnResetTela1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetTela1MouseClicked
        displaySec.setText("0");
        displayPrinc.setText("0");
        resSoma = 0;
        limpeza();
        btnApagar.setVisible(false);
    }//GEN-LAST:event_btnResetTela1MouseClicked

    private void btnApagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApagarMouseClicked
        if (!displayPrinc.getText().equals("")){
            apagarDig();
        } else {
            btnApagar.setVisible(false);
        }
    }//GEN-LAST:event_btnApagarMouseClicked

    private void btnPotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPotMouseClicked
        salvaExpressao("p");
    }//GEN-LAST:event_btnPotMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg00C;
    private javax.swing.JPanel bg01Raiz;
    private javax.swing.JPanel bg02Pot;
    private javax.swing.JPanel bg04Div;
    private javax.swing.JPanel bg10Sete;
    private javax.swing.JPanel bg11Oito;
    private javax.swing.JPanel bg12Nove;
    private javax.swing.JPanel bg14Multi;
    private javax.swing.JPanel bg20Quatro;
    private javax.swing.JPanel bg21Cinco;
    private javax.swing.JPanel bg22Seis;
    private javax.swing.JPanel bg24Menos;
    private javax.swing.JPanel bg30Um;
    private javax.swing.JPanel bg31Dois;
    private javax.swing.JPanel bg32Tres;
    private javax.swing.JPanel bg33Mais;
    private javax.swing.JPanel bg40MaisMenos;
    private javax.swing.JPanel bg41Zero;
    private javax.swing.JPanel bg42Virg;
    private javax.swing.JPanel bg43Igual;
    private javax.swing.JPanel bgAlteraModo;
    private javax.swing.JPanel bgApagar;
    private javax.swing.JPanel bgCalc;
    private javax.swing.JPanel bgThemeMode;
    private javax.swing.JLabel btnApagar;
    private javax.swing.JLabel btnCinco;
    private javax.swing.JLabel btnDivisao;
    private javax.swing.JLabel btnDois;
    private javax.swing.JLabel btnIgual;
    private javax.swing.JLabel btnMais;
    private javax.swing.JLabel btnMaisMenos;
    private javax.swing.JLabel btnMenos;
    private javax.swing.JLabel btnMulti;
    private javax.swing.JLabel btnNove;
    private javax.swing.JLabel btnOito;
    private javax.swing.JLabel btnPot;
    private javax.swing.JLabel btnQuatro;
    private javax.swing.JLabel btnRaiz;
    private javax.swing.JLabel btnResetTela1;
    private javax.swing.JLabel btnSeis;
    private javax.swing.JLabel btnSete;
    private javax.swing.JLabel btnThemeMode;
    private javax.swing.JLabel btnTres;
    private javax.swing.JLabel btnUm;
    private javax.swing.JLabel btnVirgula;
    private javax.swing.JLabel btnZero;
    private javax.swing.JLabel displayPrinc;
    private javax.swing.JLabel displaySec;
    private javax.swing.JLabel titleCalc;
    // End of variables declaration//GEN-END:variables
}
